/**
 * @fileoverview Usage tab content, generated from docs/usage.md.
 *
 * DO NOT EDIT THIS FILE DIRECTLY. It is produced by the generator script:
 *   npm run generate:usage
 * The source of truth is docs/usage.md.
 */
export interface UsageSection {
	title: string;
	html: string;
}

export const usageSections: UsageSection[] = [
	{
		title: 'Getting started',
		html: '<p>Practice Insight is a fully client-side meditation analytics dashboard. It ingests your Insight Timer CSV export and turns it into interactive <strong>Timeline</strong>, <strong>Comparison</strong>, and <strong>Distribution</strong> views — all computed locally in your browser, so your data never leaves your machine.</p>\n<p>When you open the app, a sample dataset (the author\'s own practice data) auto-loads so you can explore immediately. Swap in your own data whenever you\'re ready.</p>\n<p><strong>Three tabs, three questions:</strong></p>\n<ul>\n<li><strong>Timeline</strong> — "How has my practice changed over time?"</li>\n<li><strong>Comparison</strong> — "How does this period stack up against that one?"</li>\n<li><strong>Distribution</strong> — "What patterns shape my practice — by day, by time, by activity?"</li>\n</ul>',
	},
	{
		title: 'Load your data',
		html: '<ol>\n<li><strong>Get your export</strong> — in Insight Timer, export your practice history as a CSV file.</li>\n<li><strong>Upload it</strong> — drag-and-drop the CSV onto the app (or click to browse). Parsing happens in a background worker, so the UI stays responsive even for large files.</li>\n<li><strong>Check the count</strong> — a badge shows how many sessions were parsed. Rows that couldn\'t be parsed are skipped and counted for you (e.g. "1,428 parsed, 2 invalid skipped").</li>\n</ol>\n<h3>CSV schema</h3>\n<p>Insight Timer exports use these columns:</p>\n<table>\n<thead>\n<tr>\n<th>Column</th>\n<th>Meaning</th>\n</tr>\n</thead>\n<tbody><tr>\n<td><code>Started At</code></td>\n<td>Local session start time (<code>M/d/yyyy h:mm:ss</code>)</td>\n</tr>\n<tr>\n<td><code>Duration</code></td>\n<td>Session length (<code>h:mm:ss</code> or <code>mm:ss</code>)</td>\n</tr>\n<tr>\n<td><code>Preset</code></td>\n<td>The preset used (empty entries become "No Preset")</td>\n</tr>\n<tr>\n<td><code>Activity</code></td>\n<td>Practice category (e.g. Meditation, Yoga, Breathing)</td>\n</tr>\n</tbody></table>\n<h3>Global filters</h3>\n<p>The control panel gives you persistent, app-wide controls:</p>\n<ul>\n<li><strong>Activity &amp; Preset</strong> — multi-select filters, dynamically built from the values in your data.</li>\n<li><strong>Unit toggle</strong> — view everything in <strong>Minutes</strong>, <strong>Hours</strong>, or <strong>Sessions</strong>.</li>\n<li><strong>Time window</strong> — quick presets (3M, 6M, 1Y, YTD, All Time) or a <strong>custom date range</strong>.</li>\n</ul>',
	},
	{
		title: 'Timeline',
		html: '<p>The Timeline tab shows your practice as a continuous time series.</p>\n<ul>\n<li><strong>Aggregate by</strong> — choose the granularity: <strong>Day, Week, Month, Quarter, Season, or Year</strong>.</li>\n<li><strong>Time Split</strong> — break the chart into separate cards per week/month/quarter/season/year to compare segments side by side.</li>\n<li><strong>Moving average</strong> — smooth out daily noise with a sliding average window.</li>\n<li><strong>Statistical overlays</strong> — toggle the <strong>mean (μ)</strong>, <strong>±1 standard deviation</strong>, and a <strong>linear trendline</strong> to see the bigger picture.</li>\n<li><strong>Zoom</strong> — use the dataZoom brush at the bottom to focus on any time range.</li>\n</ul>\n<blockquote>\n<p><strong>Seasonal rule:</strong> Seasonal years run <strong>December 22 → December 21</strong> and are labeled by their end year (e.g. "2025 Seasonal Year"). Weeks start on <strong>Monday</strong>.</p>\n</blockquote>',
	},
	{
		title: 'Comparison',
		html: "<p>The Comparison tab answers \"how does this period compare to that one?\".</p>\n<ul>\n<li><strong>Strategy</strong> — choose <strong>Period-over-Period</strong> (align several ranges from Day 1) or <strong>Sequential side-by-side</strong> (a grid of cards).</li>\n<li><strong>Add periods</strong> — set a baseline period, then add comparison targets (previous year, custom range, etc.). Each period gets its own color, which you can override.</li>\n<li><strong>Y-axis lock</strong> — keep the scale identical across series so volumes aren't visually distorted.</li>\n<li><strong>X-axis alignment</strong> — switch between <strong>Calendar</strong> dates and <strong>Elapsed days</strong> (Day 1, Day 2, …).</li>\n<li><strong>Differential tooltips</strong> — hover to see the difference between series, e.g. <code>2025: 45m | 2024: 30m | Diff: +15m (+50%)</code>.</li>\n<li><strong>Export</strong> — save any chart as a high-resolution <strong>PNG</strong> or <strong>SVG</strong>.</li>\n</ul>\n<p><strong>Example:</strong> \"Compare this year's Q1 vs last year's\" — add a period for this year's Q1, then one for last year's Q1, and overlay them.</p>",
	},
	{
		title: 'Distribution',
		html: '<p>The Distribution tab reveals behavioral patterns.</p>\n<ul>\n<li><strong>Day-of-Week</strong> — a 7-column heatmap matrix (Mon–Sun) across weeks/months/seasons, or a simple bar chart. Great for finding your most consistent day.</li>\n<li><strong>Time-of-Day</strong> — a 24-hour <strong>polar clock</strong> or an <strong>hourly histogram</strong>. Spot your morning practice vs your evening slump.</li>\n<li><strong>Activity &amp; Preset breakdown</strong> — a <strong>donut</strong> (proportional share) or <strong>stacked bar</strong> (mix over time).</li>\n<li><strong>Temporal grouping</strong> — compare by week, month, quarter, season, or year.</li>\n<li><strong>Metric</strong> — switch between <strong>total duration</strong>, <strong>session count</strong>, and <strong>average session length</strong>.</li>\n<li><strong>Threshold filter</strong> — ignore sessions under a set length to exclude accidental quick logs.</li>\n<li><strong>Comparison strategy</strong> — for grouped charts, overlay multiple periods or view them side by side.</li>\n</ul>\n<p><strong>Example:</strong> "Find my most consistent weekday" — open Day-of-Week, and the heatmap/bar shows exactly which day your practice habit is strongest.</p>',
	},
	{
		title: 'Privacy',
		html: '<p>Practice Insight is <strong>privacy-first by design</strong>:</p>\n<ul>\n<li>All parsing, statistics, and chart rendering run <strong>entirely in your browser</strong>.</li>\n<li>No data is uploaded, transmitted, or stored on any server.</li>\n<li>Close the tab and your data is gone.</li>\n</ul>\n<p>Your meditation practice is personal — it stays on your device.</p>',
	},
	{
		title: 'FAQ / Troubleshooting',
		html: '<p><strong>My CSV won\'t load / shows skipped rows.</strong>\nRows with unparseable timestamps or durations are skipped and counted. Check that your file follows the schema above (<code>Started At</code>, <code>Duration</code>, <code>Preset</code>, <code>Activity</code>) and that timestamps use <code>M/d/yyyy h:mm:ss</code>.</p>\n<p><strong>The chart is blank.</strong>\nMake sure you have data loaded and that your filters (activity, preset, date range) aren\'t excluding everything. Try the <strong>All Time</strong> preset to reset the date window.</p>\n<p><strong>Where does the sample data come from?</strong>\nIt\'s the author\'s own practice data, bundled to auto-load for demonstration. You can replace it with your own CSV at any time.</p>\n<p><strong>Do you store my data?</strong>\nNo. Everything runs locally in your browser — see <a href="#privacy">Privacy</a>.</p>\n<p><strong>How can I request a feature or report a bug?</strong>\nOpen an issue on <a href="https://github.com/yogat3ch/practice-insight/issues">GitHub</a> — there are templates for both.</p>',
	},
];
