#!/usr/bin/env node
/**
 * @fileoverview Generates src/lib/usage/usage-content.ts from docs/*.md.
 *
 * Reads each documentation markdown file in docs/, extracts the content
 * between its HTML-comment delimiters (e.g. `<!-- app-usage:start -->` /
 * `<!-- app-usage:end -->`), converts it to HTML with `marked`, sanitizes it
 * with `sanitize-html`, splits it into `##` sections, and writes a
 * deterministic TypeScript module consumed by the Usage tab.
 *
 * Each doc becomes a UsageDocument {id, title, sections}; all sections are
 * also flattened into usageSections for backward compatibility.
 *
 * The generated file is committed so the app builds without running this
 * script; a `prebuild` hook regenerates it to keep it in sync.
 */
import {marked} from 'marked';
import {mkdirSync, readdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import prettier from 'prettier';
import sanitizeHtml from 'sanitize-html';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(SCRIPT_DIR, '..');

const DOCS_DIR = resolve(ROOT, 'docs');
const OUT_PATH = resolve(ROOT, 'src/lib/usage/usage-content.ts');

// A doc is picked up when it has at least one delimiter pair.
const DELIMITER_RE = /<!--\s*app-([a-z0-9-]+):start\s*-->/;

const SOURCE_HEADER = `/**
 * @fileoverview Usage tab content, generated from docs/*.md.
 *
 * DO NOT EDIT THIS FILE DIRECTLY. It is produced by the generator script:
 *   npm run generate:usage
 * The source of truth is the markdown files in docs/.
 */
`;

// Sanitization allowlist. `img` is allowed so screenshots (authored as
// `![...](static/xxx.png)`) render in the app; the generator rewrites those
// paths to `/xxx.png` so they resolve against the deployed base URL.
const SANITIZE_OPTIONS = {
	allowedTags: [
		'h1',
		'h2',
		'h3',
		'p',
		'a',
		'ul',
		'ol',
		'li',
		'strong',
		'em',
		'code',
		'pre',
		'blockquote',
		'table',
		'thead',
		'tbody',
		'tr',
		'th',
		'td',
		'br',
		'hr',
		'img',
	],
	allowedAttributes: {
		a: ['href', 'title'],
		th: ['align'],
		td: ['align'],
		img: ['src', 'alt', 'title', 'width', 'height'],
	},
	allowedSchemes: ['http', 'https', 'mailto', 'data'],
};

// Rewrite `static/...` image srcs to `/...` (in-app base) — GitHub keeps the
// literal `static/...` path, the app serves static assets at the root.
// Works for nested paths too: `static/it_export/three_lines.png` → `/it_export/three_lines.png`.
/**
 * @param {string} src
 * @returns {string}
 */
function rewriteStaticSrc(src) {
	return src.startsWith('static/') ? '/' + src.slice('static/'.length) : src;
}

// Rewrite relative `.md` links to `#/<doc-id>` so the Usage tab can switch
// documents in place. GitHub keeps the literal relative link and navigates
// between files normally.
/**
 * @param {string} href
 * @returns {string}
 */
function rewriteDocLink(href) {
	// e.g. "it_export.md" or "usage.md" → "#/it-export" / "#/usage"
	// Doc ids use hyphens (from the delimiter `app-<id>:start`), so normalize
	// underscores in the filename to hyphens to match the generated doc id.
	const match = href.match(/^([a-z0-9_-]+)\.md$/i);
	if (match) return `#/${match[1].toLowerCase().replace(/_/g, '-')}`;
	return href;
}

// Configure marked once: rewrite static image paths and .md links via a custom
// renderer.
marked.use({
	renderer: {
		image({href, title, text}) {
			const src = rewriteStaticSrc(href ?? '');
			const titleAttr = title ? ` title="${title}"` : '';
			return `<img src="${src}" alt="${text}"${titleAttr} />`;
		},
		link({href, title, text}) {
			const out = rewriteDocLink(href ?? '');
			const titleAttr = title ? ` title="${title}"` : '';
			return `<a href="${out}"${titleAttr}>${text}</a>`;
		},
	},
});

/**
 * Extracts the delimited block for a doc id from markdown.
 * @param {string} markdown
 * @param {string} docId
 * @returns {string}
 */
export function extractUsageBlock(markdown, docId) {
	const startMarker = `<!-- app-${docId}:start -->`;
	const endMarker = `<!-- app-${docId}:end -->`;
	const start = markdown.indexOf(startMarker);
	const end = markdown.indexOf(endMarker);
	if (start === -1 || end === -1 || end <= start) {
		throw new Error(
			`Delimiters missing or out of order for doc "${docId}" ` +
				`in ${DOCS_DIR}. Expected "${startMarker}" before "${endMarker}".`,
		);
	}
	return markdown.slice(start + startMarker.length, end);
}

/**
 * Renders the delimited block to sanitized HTML string.
 * @param {string} markdown
 * @param {string} docId
 * @returns {string}
 */
export function renderUsageHtml(markdown, docId) {
	const block = extractUsageBlock(markdown, docId);
	const rawHtml = marked.parse(block, {gfm: true, breaks: false});
	return sanitizeHtml(String(rawHtml), SANITIZE_OPTIONS);
}

/**
 * Splits rendered HTML into sections by `##` heading level.
 * @param {string} html
 * @returns {{title: string; html: string}[]}
 */
export function splitSections(html) {
	const sections = [];
	/** @type {{title: string; html: string[]} | null} */
	let current = null;

	for (const line of html.split('\n')) {
		const match = line.match(/^<h2[^>]*>(.*?)<\/h2>$/);
		if (match) {
			current = {title: match[1], html: []};
			sections.push(current);
		} else if (current) {
			current.html.push(line);
		}
	}

	return sections.map(section => ({
		title: section.title,
		html: section.html.join('\n').trim(),
	}));
}

/**
 * Renders a section object to a TypeScript array entry.
 * @param {{title: string; html: string}} section
 * @returns {string}
 */
function sectionToTs(section) {
	const title = JSON.stringify(section.title);
	const html = JSON.stringify(section.html);
	return `\t{title: ${title}, html: ${html}},`;
}

/**
 * Derives a human title from a doc file, preferring the first `#` heading
 * and falling back to the humanized doc id.
 * @param {string} docId
 * @param {string} markdown
 * @returns {string}
 */
export function docTitle(docId, markdown) {
	const h1 = markdown.match(/^#\s+(.+)$/m);
	if (h1) return h1[1].trim();
	return docId
		.split(/[-_]/)
		.map(word => word.charAt(0).toUpperCase() + word.slice(1))
		.join(' ');
}

/**
 * Discovers doc ids from the files in docs/ that contain delimiters.
 * @returns {string[]}
 */
export function discoverDocIds() {
	const files = readdirSync(DOCS_DIR).filter(f => f.endsWith('.md'));
	const ids = [];
	for (const file of files) {
		const markdown = readFileSync(join(DOCS_DIR, file), 'utf8');
		const match = markdown.match(DELIMITER_RE);
		if (match) ids.push(match[1]);
	}
	return ids.sort();
}

/**
 * Reads the markdown for a given doc id from docs/.
 * @param {string} docId
 * @returns {string}
 */
function readDocMarkdown(docId) {
	const startMarker = `<!-- app-${docId}:start -->`;
	const file = readdirSync(DOCS_DIR).find(f => {
		if (!f.endsWith('.md')) return false;
		return readFileSync(join(DOCS_DIR, f), 'utf8').includes(startMarker);
	});
	if (!file) {
		throw new Error(`No docs/ file found containing "${startMarker}".`);
	}
	return readFileSync(join(DOCS_DIR, file), 'utf8');
}

/**
 * Builds the full TypeScript module content from the docs directory.
 * @returns {string}
 */
export function buildUsageContent() {
	const docIds = discoverDocIds();
	const documents = docIds.map(docId => {
		const markdown = readDocMarkdown(docId);
		const sections = splitSections(renderUsageHtml(markdown, docId));
		return {id: docId, title: docTitle(docId, markdown), sections};
	});

	const flatSections = documents.flatMap(doc => doc.sections);

	const lines = [];
	lines.push(SOURCE_HEADER);
	lines.push('export interface UsageSection {');
	lines.push('\ttitle: string;');
	lines.push('\thtml: string;');
	lines.push('}');
	lines.push('');
	lines.push('export interface UsageDocument {');
	lines.push('\tid: string;');
	lines.push('\ttitle: string;');
	lines.push('\tsections: UsageSection[];');
	lines.push('}');
	lines.push('');
	lines.push('export const usageDocuments: UsageDocument[] = [');
	for (const doc of documents) {
		lines.push('\t{');
		lines.push(`\t\tid: ${JSON.stringify(doc.id)},`);
		lines.push(`\t\ttitle: ${JSON.stringify(doc.title)},`);
		lines.push('\t\tsections: [');
		for (const section of doc.sections) {
			lines.push('\t\t\t' + sectionToTs(section));
		}
		lines.push('\t\t],');
		lines.push('\t},');
	}
	lines.push('];');
	lines.push('');
	lines.push('export const usageSections: UsageSection[] = [');
	for (const section of flatSections) {
		lines.push('\t' + sectionToTs(section));
	}
	lines.push('];');
	lines.push('');

	return lines.join('\n');
}

// CLI entry point: only run when invoked directly (not when imported by tests).
const isMain =
	process.argv[1] &&
	resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
	// Resolve the repo's .prettierrc (tabs, single quotes, etc.) so the
	// generated file matches `prettier --write` output exactly.
	const prettierConfig = await prettier.resolveConfig(OUT_PATH);
	const output = await prettier.format(buildUsageContent(), {
		...prettierConfig,
		parser: 'typescript',
	});
	mkdirSync(dirname(OUT_PATH), {recursive: true});
	writeFileSync(OUT_PATH, output);
	const docCount = discoverDocIds().length;
	console.log(
		`Generated ${OUT_PATH} with ${docCount} document(s) ` +
			`(${output.split('\n').length} lines).`,
	);
}
