#!/usr/bin/env node
/**
 * @fileoverview Generates src/lib/usage/usage-content.ts from docs/usage.md.
 *
 * Reads the markdown source of truth, extracts the content between the
 * `app-usage:start` / `app-usage:end` HTML comments, converts it to HTML with
 * `marked`, sanitizes it with `sanitize-html`, splits it into `##` sections,
 * and writes a deterministic TypeScript module consumed by the Usage tab.
 *
 * The generated file is committed so the app builds without running this
 * script; a `prebuild` hook regenerates it to keep it in sync.
 */
import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {marked} from 'marked';
import sanitizeHtml from 'sanitize-html';
import prettier from 'prettier';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(SCRIPT_DIR, '..');

const DOCS_PATH = resolve(ROOT, 'docs/usage.md');
const OUT_PATH = resolve(ROOT, 'src/lib/usage/usage-content.ts');

const START_MARKER = '<!-- app-usage:start -->';
const END_MARKER = '<!-- app-usage:end -->';

const SOURCE_HEADER = `/**
 * @fileoverview Usage tab content, generated from docs/usage.md.
 *
 * DO NOT EDIT THIS FILE DIRECTLY. It is produced by the generator script:
 *   npm run generate:usage
 * The source of truth is docs/usage.md.
 */
`;

/**
 * Extracts the delimited block from the docs file.
 * @param {string} markdown
 * @returns {string}
 */
export function extractUsageBlock(markdown) {
	const start = markdown.indexOf(START_MARKER);
	const end = markdown.indexOf(END_MARKER);
	if (start === -1 || end === -1 || end <= start) {
		throw new Error(
			`Usage delimiters missing or out of order in ${DOCS_PATH}. ` +
				`Expected "${START_MARKER}" before "${END_MARKER}".`,
		);
	}
	return markdown.slice(start + START_MARKER.length, end);
}

/**
 * Renders the delimited usage block to sanitized HTML string.
 * @param {string} markdown
 * @returns {string}
 */
export function renderUsageHtml(markdown) {
	const usageBlock = extractUsageBlock(markdown);
	const rawHtml = marked.parse(usageBlock, {gfm: true, breaks: false});
	return sanitizeHtml(String(rawHtml), {
		allowedTags: [
			'h1',
			'h2',
			'h3',
			'p',
			'a',
			'ul',
			'ol',
			'li',
			'strong',
			'em',
			'code',
			'pre',
			'blockquote',
			'table',
			'thead',
			'tbody',
			'tr',
			'th',
			'td',
			'br',
			'hr',
		],
		allowedAttributes: {
			a: ['href', 'title'],
			th: ['align'],
			td: ['align'],
		},
		allowedSchemes: ['http', 'https', 'mailto'],
	});
}

/**
 * Splits rendered HTML into sections by `##` heading level.
 * @param {string} html
 * @returns {{title: string; html: string}[]}
 */
export function splitSections(html) {
	const sections = [];
	/** @type {{title: string; html: string[]} | null} */
	let current = null;

	for (const line of html.split('\n')) {
		const match = line.match(/^<h2[^>]*>(.*?)<\/h2>$/);
		if (match) {
			current = {title: match[1], html: []};
			sections.push(current);
		} else if (current) {
			current.html.push(line);
		}
	}

	return sections.map(section => ({
		title: section.title,
		html: section.html.join('\n').trim(),
	}));
}

/**
 * Renders a section object to a TypeScript array entry.
 * @param {{title: string; html: string}} section
 * @returns {string}
 */
function sectionToTs(section) {
	const title = JSON.stringify(section.title);
	const html = JSON.stringify(section.html);
	return `\t{title: ${title}, html: ${html}},`;
}

/**
 * Builds the full TypeScript module content from markdown source.
 * @param {string} markdown
 * @returns {string}
 */
export function buildUsageContent(markdown) {
	const sections = splitSections(renderUsageHtml(markdown));
	return (
		SOURCE_HEADER +
		'export interface UsageSection {\n' +
		'\ttitle: string;\n' +
		'\thtml: string;\n' +
		'}\n\n' +
		'export const usageSections: UsageSection[] = [\n' +
		sections.map(sectionToTs).join('\n') +
		'\n];\n'
	);
}

// CLI entry point: only run when invoked directly (not when imported by tests).
const isMain =
	process.argv[1] &&
	resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isMain) {
	const markdown = readFileSync(DOCS_PATH, 'utf8');
	// Resolve the repo's .prettierrc (tabs, single quotes, etc.) so the
	// generated file matches `prettier --write` output exactly.
	const prettierConfig = await prettier.resolveConfig(OUT_PATH);
	const output = await prettier.format(buildUsageContent(markdown), {
		...prettierConfig,
		parser: 'typescript',
	});
	mkdirSync(dirname(OUT_PATH), {recursive: true});
	writeFileSync(OUT_PATH, output);
	const sectionCount = splitSections(renderUsageHtml(markdown)).length;
	console.log(
		`Generated ${OUT_PATH} with ${sectionCount} sections ` +
			`(${output.split('\n').length} lines).`,
	);
}
